### ISSUE TITLE
Add reversed usage `zm`

### ISSUE THREAD

**Issue by JoschuaSchneider** [JoschuaSchneider/mehrzahl#2]
The current `mz` implementation allows creating a formatter function bound to a number like this:

```ts
const formatter = mz(5)
formatter`number is {singular|plural}`
formatter`value of number is $value`
```

This is useful when you have one number that you need to use for multiple formatted strings. But you might also need one set string formatted to different numbers like this (I propose the name `zm` for this):

```ts
const template = zm`number is {singular|plural}`
template(5)
template(0)
```

**Comment by menghif** [comment]
Yes, I’m on it today! It’s been a busy week
